services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./reports:/app/reports
      - ./monitoring:/app/monitoring
    environment:
      - FLIGHTRISK_ENABLE_MLFLOW=0

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    ports:
      - "8501:8501"
    depends_on:
      - api
    volumes:
      - ./models:/app/models
      - ./reports:/app/reports
      - ./monitoring:/app/monitoring
    environment:
      - FLIGHTRISK_ENABLE_MLFLOW=0
